[workspace]
resolver = "2"
members = [
    "tauri-plugin",
    "supertonic",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Supertonic contributors"]
repository = "https://github.com/TheoSlater/supertonic-rs"
homepage = "https://github.com/TheoSlater/supertonic-rs"
