[workspace]
resolver = "2"
members = [
    "tauri-plugin",
    "supertonic",
    "supertonic-cli/native-synth",
]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Supertonic contributors"]
repository = "https://github.com/TheoSlater/supertonic-rs"
homepage = "https://github.com/TheoSlater/supertonic-rs"
